services:
  web:
    build: .
    ports:
      - "8084:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db: 
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: usuario_app
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: mascotas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8086:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

volumes:
  postgres_data: